function lheader(h,directory)
%path(path, 'C:\Program Files\Lumerical\FDTD\api\matlab')

code=strcat(['cd("' directory '");',...
    'format short;',...
    'switchtolayout;',...
    'delete;',...
    'clear;',...
    'newproject;']);
disp(code);
appevalscript(h,code);

end