function [data]=MPB_Run(SimType,Myctlname,Myoutname,Andro_MPBdir,workspace,Nmachine,FixedParam,CurrParam,nbands,kstart,kend,kpts,res,Niter)
%% Run MPB simulation over the seven compute nodes
Outputdir=[workspace '/Niter' num2str(Niter) '_s1' num2str(CurrParam(5),4) ...
    '_a' num2str(CurrParam(1),4) '_r1' num2str(CurrParam(2),4) '_alpha' num2str(CurrParam(3),4) ...
    '_offset' num2str(CurrParam(4),4)];
if ~isdir(Outputdir)
    unix(['mkdir ' Outputdir])
end
unix(['cp ' workspace '/' Myctlname ' ' Outputdir '/' Myctlname])
unix(['cp ' workspace '/readBands.m ' Outputdir '/readBands.m'])
unix(['cp ' workspace '/h5topng.m ' Outputdir '/h5topng.m'])
unix(['cp ' workspace '/bandplot.m ' Outputdir '/bandplot.m'])
unix(['cp ' workspace '/savetofile.m ' Outputdir '/savetofile.m'])
unix(['cp ' workspace '/Fitband.m ' Outputdir '/Fitband.m'])
unix(['cp ' workspace '/Modearea.m ' Outputdir '/Modearea.m'])
unix(['cp ' workspace '/DATAProcess.m ' Outputdir '/DATAProcess.m'])
if Nmachine~='Master'
    unix(['cp ' workspace '/machine' num2str(Nmachine) ' ' Outputdir '/machine' num2str(Nmachine)])
end
cd(Outputdir)

delete('Parameters.txt');
fileID=fopen('Parameters.txt','w');
Parameters=['Lattice Constant: ' num2str(CurrParam(1)) 'nm\n' ...
    'Slab Thickness: ' num2str(FixedParam(2)) 'nm\n' ...
    'Slot Width: ' num2str(FixedParam(3)) 'nm\n' ...
    'r1 (First hole radius): ' num2str(CurrParam(2)) 'nm\n'...
    'r2 (Second hole radius): ' num2str(FixedParam(1)) 'nm\n'...
    'r3 (All the other hole radius): ' num2str(FixedParam(4)) 'nm\n'...
    'S1 (Center-shift of the First hole): ' num2str(CurrParam(5)) 'nm\n'...
    'S2 (Center-shift of the Second hole): ' num2str(FixedParam(5)) 'nm\n'...
    'Offset (Add dielectric at the edge of the slot): ' num2str(CurrParam(4)) 'nm\n'...
    'Alpha (Squircle): ' num2str(CurrParam(3)) '\n' ...
    '\n ' ...
    'Resolution: ' num2str(res) '\n ' ...
    'Number of kpoints: ' num2str(kpts) '\n '];
fprintf(fileID,Parameters);

% if SimType=='mpbi-split'
%     if Nmachine=='Master'
%         commandstr=['ssh -C andromeda "cd ' Outputdir ' && ' Andro_MPBdir 'mpbi-split' ...
%             ' kstart=' num2str(kstart) ' kend=' num2str(kend) ...
%             ' kpts=' num2str(kpts) ' nbands=' num2str(nbands) ' res=' num2str(res) ' s1=' num2str(CurrParam(5)) ...
%             ' s2=' num2str(CurrParam(6)) ' a=' num2str(CurrParam(1)) ' r1=' num2str(CurrParam(2)) ...
%             ' r2=' num2str(FixedParam(1)) ' offset=' num2str(CurrParam(4)) ' alpha=' num2str(CurrParam(3)) ...
%             ' ' Outputdir '/' Myctlname ' |tee ' Outputdir '/' Myoutname];
%     else
%         commandstr=['ssh -C compute-0-' num2str(Nmachine) '"cd ' Outputdir ' && ' Andro_MPBdir 'mpbi-split' ...
%             ' kstart=' num2str(kstart) ' kend=' num2str(kend) ...
%             ' kpts=' num2str(kpts) ' nbands=' num2str(nbands) ' res=' num2str(res) ' s1=' num2str(CurrParam(5)) ...
%             ' s2=' num2str(CurrParam(6)) ' a=' num2str(CurrParam(1)) ' r1=' num2str(CurrParam(2)) ...
%             ' r2=' num2str(FixedParam(1)) ' offset=' num2str(CurrParam(4)) ' alpha=' num2str(CurrParam(3)) ...
%             ' ' Outputdir '/' Myctlname ' |tee ' Outputdir '/' Myoutname];
%     end
%     unix(commandstr)
% end

if SimType=='mpbi-mpi'    
    if Nmachine=='Master'
        unix(['mpirun -np 32 ' Andro_MPBdir 'mpbi-mpi'...
            ' kstart=' num2str(kstart) ' kend=' num2str(kend) ...
            ' kpts=' num2str(kpts) ' nbands=' num2str(nbands) ' res=' num2str(res) ' s1=' num2str(CurrParam(5)) ...
            ' s2=' num2str(FixedParam(5)) ' a=' num2str(CurrParam(1)) ' r1=' num2str(CurrParam(2)) ...
            ' r2=' num2str(FixedParam(1)) ' offset=' num2str(CurrParam(4)) ' alpha=' num2str(CurrParam(3)) ...
            ' ' Outputdir '/' Myctlname ' |tee ' Outputdir '/' Myoutname])
    else
        unix(['mpirun -np 12 --machinefile machine' num2str(Nmachine) ' ' Andro_MPBdir 'mpbi-mpi'...
            ' kstart=' num2str(kstart) ' kend=' num2str(kend) ...
            ' kpts=' num2str(kpts) ' nbands=' num2str(nbands) ' res=' num2str(res) ' s1=' num2str(CurrParam(5)) ...
            ' s2=' num2str(FixedParam(5)) ' a=' num2str(CurrParam(1)) ' r1=' num2str(CurrParam(2)) ...
            ' r2=' num2str(FixedParam(1)) ' offset=' num2str(CurrParam(4)) ' alpha=' num2str(CurrParam(3)) ...
            ' ' Outputdir '/' Myctlname ' |tee ' Outputdir '/' Myoutname])
    end
elseif SimType=='mpbi-split'
    if Nmachine=='Master'
        unix([Andro_MPBdir 'mpbi-split'...
            ' kstart=' num2str(kstart) ' kend=' num2str(kend) ...
            ' kpts=' num2str(kpts) ' nbands=' num2str(nbands) ' res=' num2str(res) ' s1=' num2str(CurrParam(5)) ...
            ' s2=' num2str(FixedParam(5)) ' a=' num2str(CurrParam(1)) ' r1=' num2str(CurrParam(2)) ...
            ' r2=' num2str(FixedParam(1)) ' offset=' num2str(CurrParam(4)) ' alpha=' num2str(CurrParam(3)) ...
            ' ' Outputdir '/' Myctlname ' |tee ' Outputdir '/' Myoutname])
    else
        unix(['--machinefile machine' num2str(Nmachine) ' ' Andro_MPBdir 'mpbi-split'...
            ' kstart=' num2str(kstart) ' kend=' num2str(kend) ...
            ' kpts=' num2str(kpts) ' nbands=' num2str(nbands) ' res=' num2str(res) ' s1=' num2str(CurrParam(5)) ...
            ' s2=' num2str(FixedParam(5)) ' a=' num2str(CurrParam(1)) ' r1=' num2str(CurrParam(2)) ...
            ' r2=' num2str(FixedParam(1)) ' offset=' num2str(CurrParam(4)) ' alpha=' num2str(CurrParam(3)) ...
            ' ' Outputdir '/' Myctlname ' |tee ' Outputdir '/' Myoutname])
    end
end
[datacell,bloc]=readBands(Myoutname);
data=datacell{1};
savetofile(datacell,'data.mat');
end
